version: '3.9'

services:
  nanosurvey_database:
    image: postgres:latest
    container_name: nanosurvey_database
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=Pa99w0rd!
      - POSTGRES_DB=nanosurvey
    ports:
      - 5434:5432
    networks:
      - nanosurvey-network

  nanosurvey_api:
    build:
      context: ./
      dockerfile: Dockerfile  
    ports:
      - 50001:80
    depends_on:
      - nanosurvey_database
    environment:
      - CONNECTIONSTRINGS__NANOSURVEY=User ID=appuser;Password=Pa99w0rd!;Host=nanosurvey_database;Port=5432;Database=nanosurvey
    networks:
      - nanosurvey-network

networks:
  nanosurvey-network:
    driver: bridge